### ISSUE TITLE
What does this part do?

### ISSUE THREAD

**Issue by cmorsucci** [Tauseef-Hilal/whatsapp_clone#8]
What does this url do? I can't figure out what it's pointing at or what it does exactly, thanks

`const String url = 'https://wa_notifications-1-q2097095.deta.app/new_message';`
https://github.com/Tauseef-Hilal/WhatsUp/blob/b3ab4ffdf7296e4df7b00dc2e982e65616fff295/lib/shared/repositories/push_notifications.dart#L37

**Comment by Tauseef-Hilal** [comment]
> What does this url do? I can't figure out what it's pointing at or what it does exactly, thanks
> 
> 
> 
> `const String url = 'https://wa_notifications-1-q2097095.deta.app/new_message';`
> 
> https://github.com/Tauseef-Hilal/WhatsUp/blob/b3ab4ffdf7296e4df7b00dc2e982e65616fff295/lib/shared/repositories/push_notifications.dart#L37

It points to `new_message` endpoint on my [WhatsUp Notification Server](https://github.com/Tauseef-Hilal/notification_server). I make a post request to this endpoint. The server then sends a notification to the receiver (identified by their FCM Token)

**Comment by cmorsucci** [comment]
Ah sorry, I hadn't seen your script to send push notifications. Thanks
