### ISSUE TITLE
Linux and Web (Chrome)

### ISSUE THREAD

**Issue by jowolf** [Tauseef-Hilal/whatsapp_clone#9]
I'm trying to build / run on Linux, and (secondarily) web / Chrome - on the latest main:

commit b3ab4ffdf7296e4df7b00dc2e982e65616fff295 (HEAD -> main, origin/main, origin/HEAD)
Merge: a9891e0 29f36e4
Author: Tauseef-Hilal <tantary.tauseef.atwork@gmail.com>
Date:   Tue Jan 23 17:13:50 2024 +0530
Merge branch 'main' of https://github.com/Tauseef-Hilal/whatsapp_clone

When I choose Linux, it builds OK and runs, but I get a blank screen (black)
When I choose Chrome, I get 1022 instances of "... Error: The type 'JSObject' can't be used as supertype."
and several integer overflows, eg: 
"Error: The integer literal 342568039478732666 can't be represented exactly in JavaScript."
in the shared libraries, such as:
lib/shared/models/contact.g.dart:18:7:
lib/shared/models/messages.g.dart:18:8: (and 1561:7)
...user.g.dart, etc
and a few missing methods in events/providers.dart , 
Error: The method 'typeofEquals' isn't defined for the class 'EventTarget'.
also e.hasProperty, also

The most recent stable flutter release (3.22) fixed the EnsureInitialized issue, I was using the beta release before that to get past it.

I am willing to help with the project, if I can get past these - also, I observe there is a deprecated phone_numbers package...

**Comment by Tauseef-Hilal** [comment]
> I'm trying to build / run on Linux, and (secondarily) web / Chrome - on the latest main:
> 
> 
> 
> commit b3ab4ffdf7296e4df7b00dc2e982e65616fff295 (HEAD -> main, origin/main, origin/HEAD)
> 
> Merge: a9891e0 29f36e4
> 
> Author: Tauseef-Hilal <tantary.tauseef.atwork@gmail.com>
> 
> Date:   Tue Jan 23 17:13:50 2024 +0530
> 
> Merge branch 'main' of https://github.com/Tauseef-Hilal/whatsapp_clone
> 
> 
> 
> When I choose Linux, it builds OK and runs, but I get a blank screen (black)
> 
> When I choose Chrome, I get 1022 instances of "... Error: The type 'JSObject' can't be used as supertype."
> 
> and several integer overflows, eg: 
> 
> "Error: The integer literal 342568039478732666 can't be represented exactly in JavaScript."
> 
> in the shared libraries, such as:
> 
> lib/shared/models/contact.g.dart:18:7:
> 
> lib/shared/models/messages.g.dart:18:8: (and 1561:7)
> 
> ...user.g.dart, etc
> 
> and a few missing methods in events/providers.dart , 
> 
> Error: The method 'typeofEquals' isn't defined for the class 'EventTarget'.
> 
> also e.hasProperty, also
> 
> 
> 
> The most recent stable flutter release (3.22) fixed the EnsureInitialized issue, I was using the beta release before that to get past it.
> 
> 
> 
> I am willing to help with the project, if I can get past these - also, I observe there is a deprecated phone_numbers package...
> 
> 

Thanks for showing interest! But I haven't considered supporting platforms other than Android and IOS and that's also not a plan for future. I'm also not working on this project at the moment so I have kept it on pause. If you want to contribute in other parts of the project like improving code structure and overall quality of code and make it more efficient, I would be more than happy. Anyways, thanks!
